cc_library(
    name = "web_ui",
    srcs = ["web_ui.cpp"],
    hdrs = ["web_ui.h"],
    deps = ["@boost//:boost"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "simple_web_ui",
    srcs = ["simple_web_ui.cpp"],
    hdrs = ["simple_web_ui.h"],
    copts = ["-std=c++11"],
    visibility = ["//visibility:public"],
)
